openapi: 3.0.3
info:
  title: Kafka Message Models
  version: 1.0.0
paths: {}

components:
  schemas:
    GenericKafka:
      $ref: './schemas/genericKafka.yaml#/GenericKafka'

    # audit
    AuditKafka:
      $ref: './schemas/audit/auditKafka.yaml#/AuditKafka'
    BpmAudit:
      $ref: './schemas/audit/bpm/bpmAudit.yaml#/BpmAudit'
    IpeAudit:
      $ref: './schemas/audit/bpm/ipeAudit.yaml#/IpeAudit'
    CamundaAudit:
      $ref: './schemas/audit/bpm/camundaAudit.yaml#/CamundaAudit'
    ApplicationAudit:
      $ref: './schemas/audit/application/applicationAudit.yaml#/ApplicationAudit'

    # dlq
    GenericDlq:
      $ref: './schemas/dlq/genericDlq.yaml#/GenericDlq'
    TaskDlq:
      $ref: './schemas/dlq/taskDlq.yaml#/TaskDlq'
    InstanceDlq:
      $ref: './schemas/dlq/instanceDlq.yaml#/InstanceDlq'

    # enums
    BpmType:
      $ref: './schemas/enums/bpmType.yaml#/BpmType'
